# Generated by Django 4.2 on 2024-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cart", "0002_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deliver_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
