# Generated by Django 4.2 on 2024-02-25 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_cart", "0003_order_deliver_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="deliver_to",
            new_name="deliver_by",
        ),
    ]
