# Generated by Django 4.1.7 on 2024-02-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=250)),
                ("championship", models.CharField(max_length=65)),
                ("event_date", models.DateTimeField()),
                ("preview", models.TextField()),
                (
                    "poster",
                    models.ImageField(
                        blank=True, upload_to="images/match_poster/%Y/%m/%d"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="menuposition",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_positions",
                to="app_sportbar.category",
            ),
        ),
    ]
