# Generated by Django 4.2 on 2024-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0002_alter_category_description_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/match_poster/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="menuposition",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="menuposition",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/%Y/%m/%d"),
        ),
    ]
