# Generated by Django 4.2 on 2024-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0002_alter_client_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=250,
                null=True,
                upload_to="images/avatars/%Y/%m/%d",
            ),
        ),
    ]
