# Generated by Django 4.1.7 on 2024-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0002_matchevent_alter_menuposition_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("championship", models.CharField(max_length=65)),
                ("event_date", models.DateTimeField()),
                ("preview", models.TextField()),
                (
                    "poster",
                    models.ImageField(
                        blank=True, upload_to="images/match_poster/%Y/%m/%d"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MatchEvent",
        ),
    ]
