# Generated by Django 5.0.2 on 2024-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0002_client_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/avatars/%Y/%m/%d"
            ),
        ),
    ]
