# Generated by Django 4.2 on 2024-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_sportbar",
            "0003_alter_match_poster_alter_menuposition_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="preview",
            field=models.TextField(default=models.CharField(max_length=250)),
        ),
    ]
