# Generated by Django 4.1.7 on 2024-02-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0003_match_delete_matchevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="match",
            name="championship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_sportbar.championship",
            ),
        ),
    ]
