# Generated by Django 5.0.2 on 2024-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0003_alter_client_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=250,
                null=True,
                upload_to="images/avatars/%Y/%m/%d",
            ),
        ),
    ]
