# Generated by Django 4.2 on 2024-03-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0003_alter_client_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedtable",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
