# Generated by Django 4.2 on 2024-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0004_alter_client_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuposition",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
