# Generated by Django 4.2 on 2024-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0004_alter_match_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="poster",
            field=models.ImageField(
                blank=True,
                default="static/app_sportbar/images/brand-bg.png",
                null=True,
                upload_to="images/match_poster/%Y/%m/%d",
            ),
        ),
    ]
