# Generated by Django 4.2 on 2024-03-02 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0006_alter_bookedtable_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedtable",
            name="phone",
            field=models.BigIntegerField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number shold consists of from 7 to 10 figures",
                        regex="^\\d{7,10}$",
                    )
                ]
            ),
        ),
    ]
