# Generated by Django 4.2 on 2024-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0006_alter_match_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="poster",
            field=models.ImageField(
                blank=True,
                default="images/match_poster/stadium.jpg",
                null=True,
                upload_to="images/match_poster/%Y/%m/%d",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="preview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
