# Generated by Django 4.2 on 2024-03-02 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0007_alter_bookedtable_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedtable",
            name="phone",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number should consists of 10 figures",
                        regex="^\\d{10}$",
                    )
                ]
            ),
        ),
    ]
