# Generated by Django 4.2 on 2024-03-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0008_alter_bookedtable_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedtable",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
