# Generated by Django 4.2 on 2024-03-03 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_sportbar", "0009_alter_bookedtable_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedtable",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number should consists of 10 figures",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="bookedtable",
            constraint=models.UniqueConstraint(
                fields=("client", "match"), name="this match is already booked"
            ),
        ),
    ]
